### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by HippyCraig** [1000nettles/hey-wait#1]
Im really happy to have this mod, my players are all over the place.  But I did notice a bit of a performance hit on my machine when this is enabled.  Just wanted to make you aware.

**Comment by 1000nettles** [comment]
Hey @HippyCraig thanks for posting this! This is exactly the kind of feedback I'm looking for. Can you please provide any answers that you know to the following questions:

* Number of Hey, Wait! tiles on scene?
* What kind of performance hit? FPS drop? Increased GPU load?
* Was there a specific time or circumstance when the performance hit took place?

**Comment by 1000nettles** [comment]
@HippyCraig I just pushed an update which may help your performance issues. When you have a chance can you please try testing again?

**Comment by HippyCraig** [comment]
Ok I will give it a try the answer to your first set of questions
I had 1 tile on the screen
The site seemed lag moving and navigating the site.  I had two browsers open one as the GM one as a player in incognito mode.

**Comment by HippyCraig** [comment]
ok I tired the same test again, both seem to have the same lag now.   It was only a slight lag the first time, what changed?  Just curious from coding perspective.  In general there seems to be some lag lately with foundry and my system.  I have noticed that when I have a session open and I open another window to say YouTube, the videos lag as well until I close the foundry session.  Not sure if UDP ports are getting overwhelmed.

**Comment by 1000nettles** [comment]
Ahh okay, I definitely have lag if I have two Foundry instances open at the same time, too, even without the module turned on. Also, if I have a YouTube video open. Mainly because the GPU is working so hard to accommodate everything that's going on.

Can you try the same test but with Hey, Wait! turned off? Does performance get better?

**Comment by HippyCraig** [comment]
I did with this updated version, the lag seems about the same with it on or off, sorry if that wasn't clear.  I was just adding too much detail I guess. LOL

**Comment by 1000nettles** [comment]
OH got it, haha thanks man. Closing this then.

**Comment by HippyCraig** [comment]
Thanks for getting back to me so quickly, if you need any testing done in the future let me know if I can help.
