### ISSUE TITLE
Feature Request: non-rectangular event triggers

### ISSUE THREAD

**Issue by HisWatchIsEnded** [1000nettles/hey-wait#10]
Would be amazing to draw elliptical or polygonal triggers, instead of just rectangles.

The use-case here I'm thinking of would be the range of vision of a guard in a tower at night (darkvision out to 60ft). Player token moves inside of visual range, and then "Hey Wait!"

Also, polygonal would be really useful for hex grid maps.

**Comment by 1000nettles** [comment]
I really do like this idea, but since the Hey, Wait! tiles are using the tiling system in Foundry which is locked to rectangles, I don't think it's doable without a major refactor :( Sorry, but I'll close this one for now.
