### ISSUE TITLE
Add feature to stop while dragging

### ISSUE THREAD

**Issue by Zamrod** [1000nettles/hey-wait#11]
Would it be possible to stop a token as soon as it is dragged over a wait area even before the left mouse button is released. I like to use the Token Drag Vision option and it would be nice if they were stopped before they moved their token all over the place clearing fog of war.

**Comment by 1000nettles** [comment]
This is planned, thanks for asking! I'm closing this as Issue #5 already brings this up. Since you asked for it here, I'll make sure it's the next feature released.
