### ISSUE TITLE
Other modules window shows Hey, Wait! in the title

### ISSUE THREAD

**Issue by luizbgomide** [1000nettles/hey-wait#13]
Not sure what is causing this, but I noticed that with Inline Web Browser an FX Master. See screen shots below:

![image](https://user-images.githubusercontent.com/18707781/109399409-7a706500-7921-11eb-9421-bd169e2661d3.png)
![image](https://user-images.githubusercontent.com/18707781/109399416-82c8a000-7921-11eb-8835-ca82ae210b4c.png)
![image](https://user-images.githubusercontent.com/18707781/109399429-8b20db00-7921-11eb-96e0-9e654b31fa44.png)

**Comment by 1000nettles** [comment]
Thanks for letting me know! I was just too greedy with changing the window titles. I'll fix it in the next release.

**Comment by 1000nettles** [comment]
This will be resolved in the upcoming release.

**Comment by 1000nettles** [comment]
Now resolved in version 0.4.0 available now.
