### ISSUE TITLE
Token doesn't trigger Hey, Wait tiles

### ISSUE THREAD

**Issue by DMNel** [1000nettles/hey-wait#14]
Not sure when this started, but I've been trying to set up Hey, Wait tiles and they are not working when a token steps on the tile. This is for new tiles and for tiles that were previously working.  I also removed all other modules and left only the Hey, Wait module active to see if there was a conflict, but the same issue is occurring.

**Comment by paddirn** [comment]
I'm seeing the same sort of thing, but it's almost like the tile position on the GM screen doesn't actually match the tiles that have been laid down. So I may have a tile setup across two squares, but then the two squares diagonal from the trigger tiles I see on the GM screen are the ones that will actually trigger. It doesn't seem to do this consistently though. Some tiles I placed work as expected, others are like the above where they're shifted outside of the visible trigger tiles. I just downloaded and installed the mod today.

**Comment by 1000nettles** [comment]
Thanks for the bug report. Once I fix @paddirn's concern from issue #16, I'll ask you to try again if you have time.

**Comment by 1000nettles** [comment]
@DMNel can you please let me know the version of FoundryVTT you're running, your browser, and the game system you're trying this on so I can try to recreate?

**Comment by DMNel** [comment]
![image](https://user-images.githubusercontent.com/81034029/114280311-46975d80-99fe-11eb-9584-5238e4f2abcb.png)
![image](https://user-images.githubusercontent.com/81034029/114280380-90804380-99fe-11eb-9ac7-7357336c3765.png)
I've tried using this module in two game systems and the same issue occurs in both.  The Hey Wait tiles I draw do not trigger when a token is placed on them.  
![image](https://user-images.githubusercontent.com/81034029/114280445-db01c000-99fe-11eb-8d2b-2c7dc1aa814f.png)

**Comment by 1000nettles** [comment]
Thanks for experimenting. I should have asked from the beginning, are you sure that the "Restrict GM from Triggering Tiles" option is not set in the module settings?

**Comment by DMNel** [comment]
Well, Hell.  Guess I should have figured that out myself.  Sorry to waste your time.

**Comment by 1000nettles** [comment]
It's all good :) Other folks seem to have the same issue, maybe I'll default that option to false instead.
