### ISSUE TITLE
Bug: When a "Hey Wait" tile is triggered, players are dragged from other scenes

### ISSUE THREAD

**Issue by DejayJD** [1000nettles/hey-wait#15]
In my current campaign I've been spreading a lot of my maps across different scenes, when I found out that Hey Wait isn't really compatible with that because when wait tile is triggered, it pulls every player to the active scene. 
Most of the time this ends up with them on the wrong scene with no vision and then I have to manually drag them back to their previous scene

If this is a bug this should be fixed. If this is an intentional design choice, it would be nice to have the option to disable this feature as it's problematic for groups with lots of different scenes going on

**Comment by 1000nettles** [comment]
Thanks for the suggestion - it was an intentional design choice but other people have weighed in too and want an option to disable it. It's been added and will be available in the upcoming release.

**Comment by 1000nettles** [comment]
@DejayJD this has now been changed in version 0.4.0 which is available now. It has been added as a new setting entitled "Warp Players on Tile Trigger" and is by default off.
