### ISSUE TITLE
Suggestion: Kick off a Macro

### ISSUE THREAD

**Issue by HippyCraig** [1000nettles/hey-wait#18]
It would be nice to run a macro once this is triggered.  I can see it being used to kick off a role from LMRTF for example as a perception check.  Or just present some description text and audio.  Having a macro I can call what ever I can image.

**Comment by 1000nettles** [comment]
Funny enough, this functionality was released yesterday! Unless I'm misunderstanding your ask here?

**Comment by HippyCraig** [comment]
Amazing, that's exactly what I was talking about.
