### ISSUE TITLE
Feature Request:  Only trigger on friendly disposition.

### ISSUE THREAD

**Issue by xlilcasper** [1000nettles/hey-wait#19]
Only trigger Hey Wait if the token's disposition is Friendly and/or Neutral. This would stop monsters from triggering it as well as neutral tokens (like tokens used for dancing lights).

**Comment by 1000nettles** [comment]
I love it, I think that's a really reasonable feature. I'll add it to the list for next release.

**Comment by 1000nettles** [comment]
This now exists in the latest version - v0.6.0! You will need at least FoundryVTT version 0.8.5 however.
