### ISSUE TITLE
Suggestion - traps

### ISSUE THREAD

**Issue by altair984** [1000nettles/hey-wait#2]
Your module has inspired me to think of a module that would be great, one of traps:

when a character passes through the marked area and stops, several events could occur: 

First of all, an image will jump that is visible to all players (the image of a trap, a pit, rocks, spikes, etc...)

It would be great if the trap had a menu to set it: difficulty CD, damage, description. 

So it will jump an event that will make the player throw a cd of the necessary category to avoid the trap.

In the chat a card should appear with the description of the trap, the cd needed to avoid it and below a direct roll of the trap's damage, for example: instead of showing you 2d6, but throwing the damage directly (12, 10,8,2,4,5, etc...)

**Comment by 1000nettles** [comment]
Thanks for the suggestion! I also like this idea, and it's been suggested by a couple other folks too, so I'm thinking it'd be worth exploring.

**Comment by 1000nettles** [comment]
There is a new feature in version 0.4.0 which allows you to execute an associated macro with the Hey, Wait! tile. Potentially you could have a journal entry prepared here, or something more complex, which is triggered by the macro. An example macro to show a journal entry could be:

```
JournalEntry.collection.getName("your_journal_entry_here").show();
```
