### ISSUE TITLE
Feature request: associate a macro with a Hey, Wait! tile

### ISSUE THREAD

**Issue by rsimoes** [1000nettles/hey-wait#6]
Some possibilities:
- Optional panning
- Start combat
- Specify a compendium macro by name to execute

**Comment by 1000nettles** [comment]
Optional panning is a good idea for sure, that should be a low lift. Starting combat is a tricky one though, as you would first need to set up who is going to be in the combat. Setting up a macro to execute is a cool idea - for a future version I was thinking one could drag a journal / macro / "thing" onto the Hey, Wait! tile config, to allow that "thing" to take place when the tile is triggered.

Thoughts?

**Comment by rsimoes** [comment]
- I see your point on combat. It could be subsumed under the macros feature (which would basically allow unlimited extensibility on behavior). Were it configurable directly from the tile, I suppose it'd be prudent to have at least some of the following:
  - A toggle to include all player-owned actors in the scene.
  - A combat-inclusion radius field that shows either a preview list of what is included in the specified range or a visible circle radius template that adjust as the radius is edited.
- That sounds like a good implementation for macros.

**Comment by 1000nettles** [comment]
Sounds good. I'm going to rename this issue to reflect it being surrounding adding a macro to a Hey, Wait! tile.

**Comment by 1000nettles** [comment]
Now available in version 0.4.0!
