### ISSUE TITLE
Add setting/option to pause the game when a tile is triggered

### ISSUE THREAD

**Issue by Puddinglord** [1000nettles/hey-wait#7]
This would be super useful as I use these tiles to represent traps or moments in the story where I need all the tokens to stop moving. Pausing the game would be the easiest solution, I believe.

**Comment by 1000nettles** [comment]
Sorry, I'm not sure I follow. Currently if a player-controlled token collides with a Hey, Wait! tile, the game will pause for everyone. Is there something I'm missing?

**Comment by Puddinglord** [comment]
I was trying it out as a "player" in the forge and every time I triggered the tile it would pan the screen and play the sound with the "!" but it never paused the game. It could be that because there wasn't a GM account connected at the time that it couldn't communicate back to pause the game.

**Comment by 1000nettles** [comment]
Ah got it, yeah it would work like that if there's no GM connected. AFAIK there's no way to ask the server as a player to pause the game, it must be done as a GM.

Do you forsee players playing on scenes without a GM present?

**Comment by Puddinglord** [comment]
I do not; my mistake for thinking it didn't do that. I use The Forge, which lets me join the game as a player version of myself to test what the players will see and have access to, which led me to this issue. I have confirmed that while I stay on my GM account and use the player version to trigger the tile, the game pauses like it's supposed to.

Thanks for a wonderful module!

**Comment by 1000nettles** [comment]
Ahh okay, I've never actually used The Forge before! I should give it a go. Excellent sounds good, and thanks for flagging regardless.
